superlist/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^$',						'lists.views.home_page',	name='home'),
	url(r'^lists/(\d+)/$',			'lists.views.view_list',	name='view_list'),
	url(r'^lists/(\d+)/add_item$',	'lists.views.add_item',		name='add_item'),
	url(r'^lists/new$',				'lists.views.new_list',		name="new_list")
]

lists/models.py
from django.db import models

class List(models.Model):
	pass

class Item(models.Model):
	text = models.TextField(default='')
	list = models.ForeignKey(List, default=None)

lists/views.py
from django.shortcuts import redirect, render
from lists.models import Item, List

def home_page(request):
	return render(request, 'home.html')

def view_list(request, list_id):
	list_ = List.objects.get(id=list_id)
	return render(request, 'list.html', {'list': list_})

def new_list(request):
	list_ = List.objects.create()
	Item.objects.create(text=request.POST['item_text'], list=list_)
	return redirect('/lists/%d/' % (list_.id))

def add_item(request, list_id):
	list_ = List.objects.get(id=list_id)
	Item.objects.create(text=request.POST['item_text'], list=list_)
	return redirect('/lists/%d/' % (list_.id))

lists/templates/home.html
<html>
	<title>To-Do lists</title>
</html>
<body>
	<h1>Start a new To-Do list</h1>
	<form method="POST" action="/lists/new">
		<input id="new_item" name="item_text" type="text" placeholder="Enter a to-do item">
		{% csrf_token %}
	</form>
</body>

lists/templates/list.html
<html>
	<title>To-Do lists</title>
</html>
<body>
	<h1>Your To-Do list</h1>
	<form method="POST" action="/lists/{{ list.id }}/add_item">
		<input id="new_item" name="item_text" type="text" placeholder="Enter a to-do item">
		{% csrf_token %}
	</form>

	<table id="list_table">
		{% for item in list.item_set.all %}
			<tr><td>{{ forloop.counter }}: {{ item.text }}</td></tr>
		{% endfor %}
	</table>
</body>